### ISSUE TITLE
March Checklist for v0 Release

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#58]
Work to compete before we can package a v0 VA-Spec release. 
 
**1. Statements**: Essentially done, with exception of small issue with Computational Functional Impact Statement model (pre-testing with BRCA Exchange data revealed an overlooked requirement from initial analysis)
- [ ] resolve small issue with Computational Functional Impact Statement mode (See [#21](https://github.com/ga4gh/va-spec/issues/21#issuecomment-599558584))
 
**2. Domain Entities:**  Essentially done (see  [gdoc](https://docs.google.com/document/d/1t2rjCxlTF9SBhfTePsfNN5LVAepgnHQZ3TMkiGMU8i4/edit#heading=h.msqd8i7q8b1g), [models](https://docs.google.com/spreadsheets/d/1zQU-Yv7gB7IHKIOVsTh-74BwdtgB9KQpKcWkSHZOa-Q/edit#gid=1943113734)), with exception of final touches on Sequence Feature model 
- [ ] complete domain entity model for Sequence Features (See #19)
 
**3. Value Sets**:  See #56 
- [ ] Review where we want to provide recommended value sets, define terms for each
- [ ] Decide how/where we should encode these value sets. 
 
**4. Data Types:** See #57
- [ ] Review proposal for data types to define 
 
**5. Extension Mechanisms:** See #54, #55
- [ ] Define specifics of modeling to support addition of ad hoc, custom attributes to any VA class
 
**6. Evidence and Provenance Model:** One remaining big ticket item to complete. We have assembled detailed requirements that we will review, and then propose a SEPIO-based set of models to cover the core VA types to be released in the v0 Spec.

**Comment by andrewyatz** [comment]
I think #61 should get linked into here now
